---
#Select Catalyst Cennter version, this one overwrite the default version from host file
catalyst_center_version: 2.3.7.6
# This file contains the variables for the LAN Automation workflow
lan_automation_details:
  lan_automation_session:
    - lan_automation:
        discovered_device_site_name_hierarchy: "Global/USA/New York/NYC_BLD1"
        peer_device_management_ip_address: "91.1.1.10"
        primary_device_management_ip_address: "91.1.1.14"
        primary_device_interface_names:
          - "HundredGigE1/0/2"
          - "HundredGigE1/0/29"
          - "HundredGigE1/0/35"
          - "HundredGigE1/0/33"
          - "HundredGigE1/0/31"
        ip_pools:
          - ip_pool_name: "underlay_lbpool_nyc"
            ip_pool_role: "MAIN_POOL"
          - ip_pool_name: "underlay_linkpool_nyc"
            ip_pool_role: "PHYSICAL_LINK_POOL"
        multicast_enabled: true
        redistribute_isis_to_bgp: true
        host_name_prefix: "New-York"
        isis_domain_pwd: "cisco"
        discovery_level: 5
        discovery_timeout: 40
        discovery_devices:
        - device_serial_number: "FJC27172JDX"
          device_host_name: "NYC-LAN-9300-IM1"
          device_site_name_hierarchy: Global/USA/New York/NYC_BLD1
          device_management_ip_address: "204.1.11.4"
        - device_serial_number: "FJC2721261G"
          device_host_name: "NYC-LAN-9300-IM2"
          device_site_name_hierarchy: Global/USA/New York/NYC_BLD1
          device_management_ip_address: "204.1.11.5"
        - device_serial_number: "FCW2152L02V"
          device_host_name: "NYC-LAN-9300-TRANSIT"
          device_management_ip_address: "204.1.11.6"
          device_site_name_hierarchy: Global/USA/New York/NYC_BLD1
        - device_serial_number: "FXS2429Q0WE"
          device_host_name: "NYC-LAN-9400X-EDGE1"
          device_management_ip_address: "204.1.11.7"
          device_site_name_hierarchy: Global/USA/New York/NYC_BLD1
        - device_serial_number: "FOC2722YGWW"
          device_host_name: "NYC-LAN-9300X-EDGE2"
          device_management_ip_address: "204.1.11.8"
          device_site_name_hierarchy: Global/USA/New York/NYC_BLD1
        - device_serial_number: "FCW2213G01S"
          device_host_name: "NYC-LAN-9300-EDGE3"
          device_management_ip_address: "204.1.11.9"
          device_site_name_hierarchy: Global/USA/New York/NYC_BLD2
        - device_serial_number: "FJC271915XB"
          device_host_name: "NYC-LAN-9200CX-EDGE3"
          device_management_ip_address: "204.1.11.10"
          device_site_name_hierarchy: Global/USA/New York/NYC_BLD2
        launch_and_wait: false
        pnp_authorization: false

