---
catalyst_center_hosts:
    hosts:
        catalyst_center53:
            catalyst_center_password: "xxxxxxxx"
            catalyst_center_host: 10.197.156.87
            catalyst_center_port: 443
            catalyst_center_timeout: 60
            catalyst_center_username: admin
            catalyst_center_version: 2.3.7.6
            catalyst_center_verify: false
            catalyst_center_debug: true
            catalyst_center_log_level: DEBUG
            catalyst_center_log: true
            catalyst_center_log_append: false
            catalyst_center_log_file_path: "dnac_log.log"
            #dnac_log_file_path: "../../../../catc_logs/catc_logs_10.195.243.53.log"
# iosxe_hosts:
#     hosts:
#         fusion_router1:
#             ansible_host: 198.18.133.100  # dcloud pod router #1
#             ansible_connection: ansible.netcommon.network_cli
#             ansible_user: wlcaccess
#             ansible_password: xxxxxxxx
#             ansible_become: yes
#             ansible_become_method: enable
#             ansible_network_os: cisco.ios.ios