---
#Select Catalyst Cennter version, this one overwrite the default version from host file
catalyst_center_version: 2.3.7.9
# This file contains the variables for the LAN Automation workflow
lan_automation_details:
  lan_automation_session:
    - lan_automation:
        discovered_device_site_name_hierarchy: "Global/Site_India/Karnataka/Bangalore" #This address must be superset of discovering devices address
        peer_device_management_ip_address: "205.1.1.12"
        primary_device_management_ip_address: "205.1.1.10"
        primary_device_interface_names:
          - "TenGigabitEthernet2/1/1"
          - "TenGigabitEthernet2/1/3"
        ip_pools:
          - ip_pool_name: "Bangalore_Loopback"
            ip_pool_role: "MAIN_POOL"
          - ip_pool_name: "Bangalore_Underlay_Pool"
            ip_pool_role: "PHYSICAL_LINK_POOL"
        multicast_enabled: true
        redistribute_isis_to_bgp: false
        host_name_prefix: "TB3-BGL"
        # isis_domain_pwd: "cisco"
        discovery_level: 5
        discovery_timeout: 40
        discovery_devices:
        - device_serial_number: "FOC2435L165"
          device_host_name: "TB3-BGL-Edge1"
          device_site_name_hierarchy: "Global/Site_India/Karnataka/Bangalore/BLD_1/Floor_1"
          #device_management_ip_address: "x.x.x.x" (Mandatory to give if you want automatic provisioning after Lan automation from usecases_maps playbook)
        - device_serial_number: "FJC2413E16S"
          device_host_name: "TB3-BGL-EDGE2"
          device_site_name_hierarchy: "Global/Site_India/Karnataka/Bangalore/BLD_2/Floor_1"
          #device_management_ip_address: "x.x.x.x" (Mandatory to give if you want automatic provisioning after Lan automation from usecases_maps playbook)
        launch_and_wait: true 
        pnp_authorization: false