---
catalyst_center_hosts:
    hosts:
        catalyst_center_193_234:
            dnac_password: "C!sco123"
            dnac_host: 10.195.193.234
            dnac_port: 443
            dnac_timeout: 60
            dnac_username: admin
            dnac_verify: false
            dnac_version: 2.3.7.9
            dnac_debug: true
            dnac_log_level: DEBUG
            dnac_log: true
            dnac_log_append: true
            catalyst_center_log_file_path: "dnac_log.log"
            #dnac_log_file_path: "../../../../catc_logs/catc_logs_10.195.193.234.log"
            #ansible_python_interpreter: <python interpreter path>
            #(Mandatory) DNAC Release version
            catalyst_center_debug: true
            catalyst_center_log_level: INFO
            catalyst_center_log: true
