---
catalyst_center_hosts:
    hosts:
        catalyst_center_220_76:
            catalyst_center_password: "xxxxxxxx"
            catalyst_center_host: 10.195.220.76
            catalyst_center_port: 443
            catalyst_center_timeout: 300
            catalyst_center_api_task_timeout: 3600
            catalyst_center_username: admin-automation
            catalyst_center_version: 2.3.7.9
            catalyst_center_verify: false
            catalyst_center_debug: true
            catalyst_center_log_level: DEBUG
            catalyst_center_log: true
            catalyst_center_log_append: true
            catalyst_center_log_file_path: "dnac_log.log"
            #catalyst_center_log_file_path: "../../../../catc_logs/catc_logs_10.195.220.76.log"
            #ansible_python_interpreter: <python interpreter path>
